sonar-data:
  image: postgres
  command: echo "data-only container for sonar-db"
  labels: 
    io.rancher.container.start_once: true  
sonar-db:
  image: postgres
  ports:
  - 5432:5432
  environment:
  - POSTGRES_USER=sonar
  - POSTGRES_PASSWORD=sonaracid
  volumes_from:
  - sonar-data
  labels:
    io.rancher.scheduler.affinity:host_label: usage=development
    io.rancher.sidekicks: sonar-data
sonar-conf:
  image: sonarqube
  command: echo "data-only container for sonarqube"
  labels: 
    io.rancher.container.start_once: true
sonarqube:
  image: sonarqube
  ports:
  - 9000:9000
  environment:
  - SONARQUBE_JDBC_USERNAME=sonar
  - SONARQUBE_JDBC_PASSWORD=sonaracid
  - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  volumes_from:
  - sonar-conf
  links:
  - sonar-db:db
  labels:
    io.rancher.scheduler.affinity:host_label: usage=development
    io.rancher.sidekicks: sonar-conf