registry-data:
  image: busybox
  volumes:
  - /var/lib/registry  
  command: echo "data-only container for registry"
  labels: 
    io.rancher.container.start_once: true

registry:
  image: registry:2.4.1
  ports:
  - 5000:5000
  volumes_from:
  - registry-data
  # volumes:
  # - /certs/registry:/certs
  # - /auth:/auth
  # environment:  
  # - REGISTRY_AUTH=htpasswd
  # - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
  # - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd 
  labels:
    io.rancher.scheduler.affinity:host_label: usage=development
    io.rancher.sidekicks: registry-data

registry-frontend:
  image: konradkleine/docker-registry-frontend:v2
  ports:
  - "0.0.0.0:7080:80"
  environment:  
  - ENV_DOCKER_REGISTRY_HOST=registry
  - ENV_DOCKER_REGISTRY_PORT=5000  
  #- ENV_USE_SSL=yes
  #- ENV_DOCKER_REGISTRY_USE_SSL=1
  # volumes:
  #- /certs/frontend/domain.crt:/etc/apache2/server.crt:ro
  #- /certs/frontend/domain.key:/etc/apache2/server.key:ro
  links:
  - registry:registry
  labels:
    io.rancher.scheduler.affinity:host_label: usage=development